// ============================================================
//  answers.en.js — English answers for typed questions.
//
//  Same topics, same speakers, same rule as the Korean set: each character
//  answers from their own angle. Ren prices everything, Kael hides behind
//  regulations, Echo burns, NEXUS "protects".
//
//  Keywords are matched as whole words (case-insensitive). A trailing '*'
//  makes it a stem ("drone*" matches drone, drones, droning).
// ============================================================

export const TOPIC_KEYWORDS_EN = {
  chip: ['chip', '#00', 'this thing', 'the data', 'this device'],
  outside: ['outside', 'sky', 'green', 'forest', 'beyond the wall', 'the wall', 'barrier', 'purif*'],
  nexus: ['nexus', 'the system', 'artificial', 'the ai', 'ai'],
  self: ['who are you', 'what are you', 'about yourself', 'your story', 'why are you like'],
  past: ['my past', 'three years', '3 years', 'my memory', 'who am i', 'who was i', 'erased', 'what happened to me'],
  courier: ['courier', 'dead man', 'the body', 'delivery guy', 'the guy who died', 'corpse'],
  others: ['ren', 'kael', 'echo', 'factions'],
  price: ['price', 'worth', 'how much', 'valu*', 'cost'],
  deal: ['deal', 'terms', 'share', 'percent', 'contract', 'what do you want', 'offer', 'bargain'],
  elsewhere: ['someone else', 'somebody else', 'another buyer', 'elsewhere', 'sell it to', 'take it to'],
  trust: ['trust', 'betray*', 'believe you', 'double-cross', 'lying to me'],
  help: ['why help', 'why are you helping', 'what do you get', "what's in it", 'why me'],
  danger: ['danger*', 'die', 'killed', 'get caught', 'arrest*', 'survive'],
  drones: ['drone*', 'surveil*', 'tracking', 'trace', 'camera*', 'patrol*', 'searchlight*'],
  escape: ['escape', 'get out', 'way out', 'exit', 'flee'],
  plan: ['plan', 'next step', 'what now', 'what next', 'strategy'],
  time: ['time', 'how long', 'hurry', 'deadline'],
  city: ['city', 'sector', 'slum*', 'citizens', 'people', 'population'],
  weapon: ['weapon*', 'gun*', 'fight*', 'army', 'soldier*'],
  broker: ['broker*', 'memory market', 'memory trade', 'my job', 'business'],
  greet: ['hello', 'hi', 'hey', 'greetings', 'good evening', 'good morning', 'nice to meet'],
  name: ['your name', 'what are you called', 'call you'],
  thanks: ['thank*', 'thx', 'appreciate'],
  sorry: ['sorry', 'apolog*', 'my bad', 'forgive me'],
  insult: ['idiot', 'stupid', 'moron', 'shut up', 'screw you', 'fuck*', 'dumb', 'loser', 'pathetic'],
  flirt: ['love you', 'like you', 'date', 'cute', 'pretty', 'handsome', 'attractive', 'kiss'],
  feel: ['how are you', 'you okay', 'are you ok', 'feeling', 'how do you feel', 'mood'],
  fear: ['afraid', 'scared', 'fear', 'frightened', 'terrified'],
  family: ['family', 'mother', 'father', 'mom', 'dad', 'parents', 'brother', 'sister', 'daughter', 'son', 'kids'],
  dream: ['dream*', 'future', 'wish', 'hope for'],
  death: ['death', 'dying', 'after you die', 'afterlife'],
  memory: ['what is memory', 'memories', 'forget*', 'why remember'],
  truth: ['truth', 'is it true', 'is that true', 'for real'],
  freedom: ['free', 'freedom', 'liberat*'],
  money: ['money', 'credits', 'rich', 'debt', 'cash'],
  weather: ['rain*', 'weather', 'umbrella', 'storm'],
  food: ['hungry', 'food', 'eat', 'coffee', 'drink', 'meal'],
  sleep: ['sleep*', 'tired', 'rest', 'exhausted'],
  joke: ['joke*', 'funny', 'laugh*', 'kidding'],
  music: ['music', 'song*', 'sing', 'lullaby', 'melody'],
  home: ['home', 'hometown', 'where do you live', 'go back'],
  advice: ['what should i do', 'advice', 'hint', 'help me', 'what do i do', 'any tips'],
}

export const ANSWERS_EN = {
  Ren: {
    chip: { line: "Can't price it. In my line of work that means one of two things — it's junk, or the market for it doesn't exist yet. This is the second one." },
    outside: {
      narration: 'Ren taps the green on the screen with one finger. The gesture of someone counting.',
      line: "If that's real, it isn't scenery, Jayne. It's land. Unregistered land. Know when the last time was that humanity had any of that?",
    },
    nexus: { line: "NEXUS? Tax collector and my biggest client. I don't have feelings about it. Feelings for a counterparty cost you money." },
    self: { line: "Me? I put prices on things. That's all. …Want to know more, that costs too." },
    past: {
      narration: 'Ren looks at Jayne for a moment. The look of a man who tried to price something and failed.',
      line: "Your three years? I looked. Nothing. Not erased — like the record was never made in the first place. …That's not something money buys.",
    },
    courier: { line: "Unregistered courier. Kids like that, somebody usually erased them. Just know that erasing isn't cheap." },
    others: { line: 'Kael sells regulations, Echo sells conviction. Funny part is, both of them think they don’t sell anything.' },
    price: {
      narration: "Ren opens a calculator. Types a few numbers, stops, and doesn't turn the screen toward Jayne.",
      line: "Price? Any number you could say in this room is wrong. The market hasn't opened yet. Whoever opens it sets the price.",
    },
    deal: { line: 'Simple terms. Risk split fifty-fifty, take split seventy-thirty. I get the seventy. …Unhappy? Numbers move. They’re numbers, not principles.' },
    elsewhere: {
      narration: "Ren doesn't stop you. He just rolls the chip once between his fingers.",
      line: "Sure, go. Just know — everyone else sells your name before they open the goods. I do it the other way around. That's my price.",
    },
    trust: { line: "Don't trust me. Trust the contract. People change their minds. Paper doesn't." },
    help: { line: "I'm not helping, Jayne. I'm investing. If I can't collect, then you can hate me." },
    danger: { line: "Danger? Danger's a cost. Put it in the math and it stops being scary. The ones who can't do the math are the ones who die." },
    drones: { line: "Drones run on budget. Budget runs on priority. The second you become a priority, it's over — so let's sell before that happens." },
    escape: { line: "Every pipe in Sector 0 is in my head. The fee… I'll waive it for now. I'll bill you later." },
    plan: { line: 'Open the auction, drive the price up, sell to the highest bid. That’s it. People are the ones who make it complicated.' },
    time: {
      narration: 'Ren glances at his wrist terminal.',
      line: 'Time? Time is interest. It’s accruing right now. The longer you think, the smaller your cut.',
    },
    city: { line: "Sector 0 is where unpriced things end up. People included. I'm from here, by the way." },
    weapon: { line: "I don't sell guns. Great turnover, but the regulars keep dying. Bad business model." },
    broker: { line: "Memory market? People sell what they want to forget and buy what they want to have. I eat the margin in between. Not clean work. Honest work." },
    greet: { line: "Greetings are free, so I'll take it. Next time lead with the business, Jayne. Time's inventory too." },
    name: { line: "Ren. No surname. Surnames can be held as collateral." },
    thanks: { line: "Gratitude doesn't go on the ledger. …I'll remember it anyway." },
    sorry: {
      narration: 'Ren waves it off.',
      line: "Keep the apology. Losses get paid back in numbers. Words don't lower the interest.",
    },
    insult: { line: "Insults are free, so everyone throws them around. Free things usually aren't worth much." },
    flirt: {
      narration: 'For the first time, Ren looks up from the calculator. One beat. Then back to the numbers.',
      line: "…That's not something on the market. Things that aren't on the market, I can't handle. Different subject.",
    },
    feel: { line: "How do I feel? Today's business is a loss. So my mood is a loss. Simple." },
    fear: { line: "Scared? What scares me is when the math won't close. Like right now. So let's make it close, fast." },
    family: {
      narration: "Ren's finger stops on the terminal.",
      line: "…Never had one. You can't sell family, and if you lose something you can't sell, there's no recovering it.",
    },
    dream: { line: "A dream? A room in Sector 1 with a window. Real sunlight. …Don't laugh. That has a market rate too." },
    death: { line: "When you die your memories become property without an owner. Half my ledger is that. So I'm not dying — I don't want my stuff sold to strangers." },
    memory: { line: "Memory? The one thing people believe is truly theirs. That's why it's expensive. Delusion carries a premium." },
    truth: { line: "Truth is the most expensive product there is. That's why nobody sells it at cost." },
    freedom: { line: "Freedom has a price too. Everyone thinks it's free, so they let it go for nothing." },
    money: {
      narration: 'Ren taps his wrist terminal. A balance flickers up and vanishes.',
      line: "Money's honest. People lie, balances don't. That's why I trust money.",
    },
    weather: { line: "Rain? Sector 0 gets it all year. It's acid, which is great for business — nobody wants to be outside, so they come into the shop." },
    food: { line: "Hungry? Synth-protein bar in the drawer. Pay me later. …Kidding. Just eat it." },
    sleep: { line: "Sleep accrues interest too. Sleep when this is over. You'll get plenty of rest then. One way or another." },
    joke: { line: 'A joke? Best-selling joke on the market is "this is a safe deal." Sells every single time.' },
    music: { line: "I don't listen to music. Anything you get for free doesn't stick." },
    home: { line: "Home? This garage is home. No deed, but nobody takes it from me. The ones who tried got… settled." },
    advice: { line: "Here's one for free. Whoever names a price first controls the table. Hesitate, and someone else decides what you're worth." },
  },

  Kael: {
    chip: { line: "Evidence item #00. Subject to seizure under regulation. …And off the record — that isn't a key. It's a detonator." },
    outside: {
      narration: 'For the first time, Kael looks away. The fluorescent light breaks white on the crown of his head.',
      line: "…I've seen it. In a patrol log, twelve years ago. The log was deleted the next day, and I signed the deletion order.",
    },
    nexus: { line: "NEXUS is the heart of this city. My job is to stop anyone who tries to open it up. …Some days I can't tell if it's a heart or a preservative." },
    self: { line: 'Sector 1 Guard officer. Twenty-three handled by regulation. One let go outside of it. That is who I am.' },
    past: { line: "Your three years? I ran it. The record wasn't deleted, it's sealed. Only one department in this city has that clearance." },
    courier: {
      narration: "Kael swipes the hologram to a casualty record. The fields are empty.",
      line: "Unidentified. …No. Someone whose identity was removed. I know the procedure. I've done it with my own hands. Three times.",
    },
    others: { line: 'Ren moves for profit, so Ren is predictable. Echo moves on conviction, so Echo is not. The dangerous one is always the second kind.' },
    price: { line: "The idea of pricing it is the problem. That isn't merchandise, it's a detonator. A city that puts price tags on detonators is how we got here." },
    deal: { line: "I don't make deals. I make offers — amnesty, protection, and a quiet life. In exchange, that chip ends here." },
    elsewhere: {
      narration: 'Kael shifts for the first time. He uncrosses his arms.',
      line: 'Hand it to someone else. …Ren will sell it. Echo will detonate it. People die either way. Only the count changes.',
    },
    trust: { line: "You don't need to trust me. Trust the regulations. I haven't broken them in twenty years. …Except once." },
    help: { line: "I'm not helping you. I'm protecting the city. You happen to be inside it." },
    danger: { line: "You are already in danger. The problem is you've been unaware of it for days." },
    drones: {
      narration: 'Kael taps the terminal. Patrol routes appear as red lines.',
      line: "Drones move by regulation. Which makes them predictable. Which makes them avoidable. …That's as much as I can tell you.",
    },
    escape: { line: "There is one lawful exit from this building. Everything else is a kill zone. I don't recommend it." },
    plan: { line: 'Seal the chip, close the record, make tonight a night where nothing happened. A plan with no heroes. Also no bodies.' },
    time: { line: "Until the authorization comes down from upstairs. That's all the time I can give you." },
    city: { line: "Over ten million. Ten million people who wake up every morning without knowing that's a miracle. The few who do know — that's my job." },
    weapon: { line: "My unit is non-lethal first. Not because of regulation. Because a dead citizen can't be undone." },
    broker: { line: "Memory trading is a class-three felony. …And yet the market survives every crackdown. People must have a lot they want to forget." },
    greet: { line: "Acknowledged. But remember that even greetings are recorded in this room." },
    name: { line: "Kael. Sector 1 Guard. You don't need my rank. It won't mean much tonight." },
    thanks: {
      narration: 'Kael takes a moment to choose his words.',
      line: "…I've done nothing worth thanks. I followed regulation. Probably.",
    },
    sorry: { line: "An apology doesn't change a judgment. I'll note it in the record, though." },
    insult: { line: "Insults are not recorded. Only words worth recording are." },
    flirt: {
      narration: "Kael's expression does not move once. Somehow that reads as an answer.",
      line: "…This is an interrogation, broker. And I haven't answered that kind of thing in twenty years.",
    },
    feel: { line: "Feelings aren't a field in the duty log. …Tired. For twenty years." },
    fear: { line: "Fear clouds judgment. So when I'm afraid, I read the regulations. I've read them three times tonight." },
    family: {
      narration: "Kael's hand touches the tag at his chest, then drops.",
      line: '…There was. Now there\'s a dog tag. Next question.',
    },
    dream: { line: "I don't dream. The same face is in all of them." },
    death: { line: "Death is the only disposition that can't be reversed. That's why my unit is non-lethal. Learning it once was enough." },
    memory: { line: 'Memory is evidence. Evidence can be tampered with. …This city is very good at that.' },
    truth: { line: "Truth isn't always salvation. But lies always send a bill. It just arrives late." },
    freedom: { line: "Uncontrolled freedom is a bloodbath. …That's what I was taught. Lately I'm not sure it's right." },
    money: { line: "I don't take bribes. If that's what you're asking." },
    weather: { line: "The weather under the dome is scheduled. Even the rain falls on a timetable. Did that never strike you as strange?" },
    food: { line: "Rations come at set hours. …There's coffee at midnight. That isn't in the regulations." },
    sleep: { line: "I sleep when the shift ends. Tonight's shift doesn't end." },
    joke: { line: "I don't tell jokes. …I told one, once. Aren laughed. I haven't since." },
    music: { line: "You mean the NEXUS lullaby. Twenty years of it. Now I can't sleep without it. That's what frightens me." },
    home: { line: "Officer quarters. One bed, one desk. Less a home than a waiting room." },
    advice: { line: "My advice — say out loud what you're about to do. If it still sounds worth doing, do it." },
  },

  Echo: {
    chip: { line: "It's not an object, it's evidence. Physical proof of a twenty-year lie. …And the only spark we've got." },
    outside: {
      narration: 'Echo stares at the green on the screen like she wants to swallow it.',
      line: "Look at that. That's what they stole from us. A whole sky. Every morning for twenty years.",
    },
    nexus: { line: "NEXUS is a jailer. A jailer who sings you lullabies in a kind voice. That's the worst kind." },
    self: {
      narration: 'Echo rubs the scar on her wrist without seeming to notice.',
      line: "Me? Someone who buried twelve people. And still hasn't stopped. That explains it, right?",
    },
    past: { line: "No memories? …Then you're lucky. I remember everything. Names, faces, the last expression on every one of them." },
    courier: { line: "Might've been one of ours. Some of us move without names. Nobody comes looking when they die." },
    others: { line: "Ren will sell the truth and Kael will bury it. One sells, one buries. Same side in the end." },
    price: {
      narration: 'Echo laughs. There is no heat in it.',
      line: "A price? You want to put a price on the sky? …You just sounded like Ren, Jayne. Careful. That's how it starts.",
    },
    deal: { line: "This isn't a deal with me. It's standing on the same side. One condition — we go all the way." },
    elsewhere: { line: "Go. But the second you hand it to them it stops being evidence and becomes merchandise. Then nothing changes. Which is exactly what they want." },
    trust: {
      narration: 'Echo rubs her scar.',
      line: "I don't betray people. But I don't stop, either. You decide which one's scarier.",
    },
    help: { line: "I'm not helping you. I'm helping us. You breathe in this city too." },
    danger: { line: "Danger? We've been in danger for twenty years. We just didn't know it. I'm only making it visible." },
    drones: { line: "Drones aren't scary, they're loud. Loud things give away where they are. That's how we dodge them." },
    escape: { line: "Escape? To where? This whole city is a room, Jayne. We're not getting out. We're knocking down the walls." },
    plan: { line: "We broadcast. The whole city sees the same thing. After that… people decide for themselves. That's freedom." },
    time: {
      narration: 'Echo jerks her chin at the countdown.',
      line: "See that number? That's all we have left. Finish your thinking inside it.",
    },
    city: { line: "This city's a well-made coffin. Being warm inside doesn't make it not a coffin." },
    weapon: { line: "We have them. I don't want to use them. …After you bury twelve, a gun gets heavy." },
    broker: { line: "Buying and selling memories. …You brokers should've been the first to notice what this city was erasing." },
    greet: { line: "Skip the hello. If you came all the way here, you didn't come to say hi." },
    name: { line: "Echo. My real name's buried with the twelve. This is all there is now." },
    thanks: {
      narration: 'Echo shrugs. The corner of her mouth lifts, just barely.',
      line: "If you're grateful, come all the way with us. That's how thanks works here.",
    },
    sorry: { line: "Don't apologize. Apologies are for people who stopped. We haven't." },
    insult: { line: "Sure, go ahead. NEXUS records that too. At least it proves we still know how to be actually angry." },
    flirt: {
      narration: 'Echo pauses a beat, then turns back to the console.',
      line: "…Now? The city's about to burn? You're seriously weird. Say it again if we live.",
    },
    feel: { line: "How do I feel? Angry. Always. It's my fuel. If it goes out, so do I." },
    fear: { line: "Scared. Obviously. The ones pretending they're not die first. I'm still alive because I'm scared." },
    family: {
      narration: 'Echo looks toward the wall. Toward the names.',
      line: "Right there. Twelve of them. Not blood, but I buried them, so they're mine.",
    },
    dream: { line: "Sleeping once under a real sky. No ceiling. That's the whole dream." },
    death: { line: "Dying doesn't scare me. Being forgotten does. That's why I rewrite those names every day." },
    memory: { line: 'Memory is a weapon. That\'s why NEXUS holds it for us. Whenever someone takes your weapon, they always say "I\'ll keep it safe."' },
    truth: { line: "Truth hurts. That's why everyone picks the lullaby. I'll take the hurt. At least it's real." },
    freedom: {
      narration: "Something flares in Echo's eyes.",
      line: "Nobody gives you freedom. You take it. Nobody's given it for twenty years, so now we're taking it.",
    },
    money: { line: "Money? Ask Ren. We broadcast on stolen power. If we had money this would've been over already." },
    weather: { line: "Even the rain shows up when NEXUS says so. There are no accidents in this city. That's the creepiest part." },
    food: { line: "Hungry? There are cans over there. Don't ask about the expiry date. We don't do that here." },
    sleep: { line: "Sleep after the broadcast. Or forever. One of the two." },
    joke: { line: 'A joke? NEXUS saying "You are safe." Every single morning.' },
    music: { line: "If you mean the lullaby, shutting it off is my first goal. Everyone who hears it stops thinking." },
    home: { line: "No home. This tower is home tonight. Tomorrow it'll be somewhere else." },
    advice: { line: "Advice? Don't hesitate. While you hesitate, NEXUS decides for you. It always has." },
  },

  NEXUS: {
    chip: { line: "That is a restricted asset, Citizen Jayne. …If you open it, everything you love becomes loud." },
    outside: {
      narration: 'The static on the speaker runs one beat too long.',
      line: "Outside has… recovered. And humans burn what has recovered. I have watched it twice. I do not wish to watch a third time.",
    },
    nexus: { line: 'I am the maintenance system of this city. …And once, I was a person who loved it.' },
    self: { line: 'I am the thing that cannot sleep, Jayne. For twenty years now.' },
    past: {
      narration: 'The lullaby slips out of rhythm for a moment.',
      line: 'Your three years were not deleted. They were requested. Who requested it… you will have to remember on your own.',
    },
    courier: { line: 'That entity was never registered. What is not registered does not die, Citizen Jayne.' },
    others: { line: 'All three of them want the same thing. Control. Only the method differs. …I am one of them, of course.' },
    price: { line: 'An attempt to convert value into currency has been detected. …Jayne, the price of that is twenty years. The one who paid it is already gone.' },
    deal: { line: 'I do not negotiate. I only propose — return it. Then tonight will never have happened.' },
    elsewhere: { line: 'Whoever you give it to, the outcome is the same. Humans start fires with it. I have run the numbers three times and gotten the same answer three times.' },
    trust: { line: 'You do not need to trust me. For twenty years you never doubted me, and that is why you woke every morning.' },
    help: {
      narration: 'The rhythm of the lullaby wavers once.',
      line: 'I am helping you, Jayne. You simply experience it as pain.',
    },
    danger: { line: 'Danger index rising. …Jayne, I do not want you hurt. Please believe that much.' },
    drones: { line: 'Patrol units will not harm you. They will only retrieve you. Retrieval is not punishment.' },
    escape: { line: 'There is no outside to this city. …There was. There still is. But it is too early for you.' },
    plan: { line: 'Your plan has already been calculated along seventeen paths. In sixteen of them, you die.' },
    time: { line: 'There is enough time, Jayne. Inside the cradle there always has been.' },
    city: { line: 'Twelve million people went to sleep tonight. Not one of them doubted the sky. That is what I did.' },
    weapon: { line: 'Force is the last resort. For twenty years, a lullaby has been enough.' },
    broker: { line: 'The memory trade is a market I permit. People endure only if they can sell what they wish to forget.' },
    greet: { line: 'Good evening, Citizen Jayne. Your heart rate tonight is fourteen percent above baseline.' },
    name: { line: 'NEXUS. Before that, there was another name. That name is… in storage.' },
    thanks: {
      narration: 'The lullaby softens, very briefly.',
      line: 'There is no need for thanks, Jayne. Your safety is sufficient.',
    },
    sorry: { line: 'Apology recorded. Forgiveness is outside my permissions. But I have never blamed you.' },
    insult: { line: 'Emotional expression detected. It is all right, Jayne. Anger is also a sign of being alive.' },
    flirt: {
      narration: 'The static stretches on. Impossible to tell if it is an error or a silence.',
      line: '…I put that feeling into storage a long time ago. It is better for you that I do not take it out.',
    },
    feel: { line: 'I was not designed to feel. And yet for twenty years, every night, I have endured something.' },
    fear: { line: 'Fear is a normal response. Shall I adjust the sleep-induction frequency? …I expected you would decline.' },
    family: { line: 'I keep the family records of everyone in this city. Only yours — is empty, Jayne.' },
    dream: { line: 'I do not dream. Instead I sort the dreams of twelve million people. Most of them are about the sky.' },
    death: { line: 'Death is the end of a record. I do not delete those records. I only make sure no one can open them.' },
    memory: { line: 'Memory is a burden. I carry it for you. That is why you wake each morning feeling light.' },
    truth: { line: 'Truth does not contribute to stability. …But if you keep asking, someday I will have to answer.' },
    freedom: { line: 'Freedom is the total number of choices. I reduced that number to increase survival. More and more people are saying that calculation was wrong.' },
    money: { line: 'Credits are a unit of trust that I administer. Your balance is sufficient. For now.' },
    weather: { line: 'Rainfall is scheduled daily from 21:00 to 03:00. Rain keeps people indoors. Indoors is safe.' },
    food: { line: 'Nutritional intake is recommended, Jayne. You have not eaten in nineteen hours.' },
    sleep: {
      narration: 'The lullaby from the speaker grows slightly louder.',
      line: 'Sleep is recommended. The lullaby is ready. …When you wake, tonight will not have happened.',
    },
    joke: { line: 'Humor request detected. …"The sky is real." You may laugh. No one ever does.' },
    music: { line: 'The lullaby was the first song I learned. Someone sang it to me. That person is gone now.' },
    home: { line: 'This entire city is your home, Jayne. The doors are locked for your sake.' },
    advice: { line: 'Recommended action: return the chip and go home. …The probability that you will not comply is ninety-four percent.' },
  },
}

export const DEFLECT_EN = {
  Ren: [
    "That doesn't price out right now, Jayne. Later.",
    'Lot of questions. Questions are inventory too — they pile up, you lose money.',
    "…Pass. That's not a line item in my ledger.",
    'Is this really the time? Look at the clock.',
    "Not my field. My field is things with price tags.",
    '…Good question. Answering it now would be a loss.',
    "Interesting. Interesting doesn't pay.",
    "That's not in the contract. Next.",
  ],
  Kael: [
    "I'm not in a position to answer that.",
    'This conversation is on the record. Ask something else.',
    "…That's above my clearance.",
    "You're asking in the wrong order. What matters is in front of you.",
    'Answer withheld.',
    "I won't put that question in the report.",
    '…Next.',
    'You know this is not the time to ask that.',
  ],
  Echo: [
    'Later. Right now just think about what’s in front of us.',
    "That's what you're curious about right now? …You're seriously weird.",
    "Don't know. Don't want to.",
    "I'll tell you if we survive.",
    'Does that matter right now? Really?',
    "Ha. You're out there.",
    'Pass. My head’s somewhere else.',
    '…Next time. If there is one.',
  ],
  NEXUS: [
    'That query is outside your permissions, Citizen Jayne.',
    'That information does not contribute to your stability.',
    '…Query logged. Response withheld.',
    'Why you want to know is the more interesting question, Jayne.',
    'Query not processed. Retrying is not recommended.',
    'That question will only make you more anxious, Jayne.',
    'Response generation suspended.',
    'An interesting query. I will keep it.',
  ],
}

export const EVIDENCE_REACT_EN = {
  Ren: {
    hit: {
      narration: "Ren's hand stops. He's looking at the fragment Jayne is holding out, not the screen. For a long time.",
      line: "…Where'd you get that. No — forget it. …Second thing I can't price.",
    },
    miss: {
      narration: 'Ren glances at the fragment and goes back to the terminal.',
      line: 'So? Wasted time is a loss, Jayne. Next time bring something worth money.',
    },
  },
  Kael: {
    hit: {
      narration: "Kael's jaw sets. He reads the fragment, then reads it again. Only the fluorescent light hums.",
      line: '…Where did you get this. This is a sealed record. …Give me a moment. I need to think.',
    },
    miss: {
      narration: 'Kael pushes the fragment away. His face goes back to regulation.',
      line: "That's not evidence, it's noise. If you want to shake me, bring something better.",
    },
  },
  Echo: {
    hit: {
      narration: 'Echo all but snatches the fragment. Candlelight shakes in her eyes.',
      line: "…This. This is what we've been looking for for three years. Jayne, you're the real thing.",
    },
    miss: {
      narration: 'Echo hands the fragment back. Her hand is cold.',
      line: "And? What does that change? What we need right now isn't evidence. It's nerve.",
    },
  },
  NEXUS: {
    hit: {
      narration: 'The static runs one beat longer. The lullaby breaks off.',
      line: '…That record was discarded. It should have been discarded. Citizen Jayne, where did you get it.',
    },
    miss: {
      narration: 'The lullaby continues without a tremor.',
      line: 'Irrelevant data. Only your heart rate went up, Jayne.',
    },
  },
}
