// ============================================================
//  키워드 — 화제 42 → 80. 플레이어가 실제로 치는 말을 더 넓게 받는다.
//  한국어는 부분 문자열, 영어는 단어 단위(끝에 '*'면 어간)로 맞춘다.
//
//  짧은 한국어 키워드는 다른 말 속에 숨어 오탐을 낸다("잠"→"잠깐",
//  "집"→"집중"). 그래서 조사·어미를 붙인 형태로 둔다.
// ============================================================

export const MORE_KEYWORDS = {
  age: ['몇 살', '나이가', '나이는', '몇살'],
  place: ['여기 어디', '여긴 어디', '여기가 어디', '이곳은', '여긴 뭐'],
  lien: ['리엔이', '리엔은', '리엔 누구', '설계자'],
  aren: ['아렌', '인식표'],
  dome: ['돔이', '돔은', '돔 안', '돔을', '울타리'],
  collapse: ['대붕괴', '20년 전', '이십 년 전', '그때 무슨'],
  guard: ['경비대', '경비대는', '보안국', '경찰', '진압'],
  rebels: ['반군', '반군은', '반군이', '해적 방송', '저항'],
  auction: ['경매', '낙찰', '입찰'],
  ledger: ['장부', '기록부', '분할'],
  help_me: ['도와줘', '도와 줘', '살려줘', '도움이 필요'],
  together: ['같이 가', '함께 가', '동료', '한 편', '우리 편'],
  leave: ['가도 돼', '떠날', '그만둘', '빠질래', '안 할래'],
  hurt: ['다쳤', '아파서', '아파요', '아프', '너무 아파', '피가', '상처'],
  kill: ['날 죽일', '나를 죽일', '죽일 거', '쏠 거', '해칠 거'],
  lying: ['거짓말하는', '거짓말 하는', '속이는 거', '뻥', '사기'],
  secret: ['비밀', '숨기는', '말 안 한'],
  regret: ['후회', '되돌리고', '다시 하면'],
  happy: ['행복', '기뻐', '즐거워'],
  love: ['사랑이 뭐', '사랑해 본', '사랑한 사람', '연인'],
  god: ['신이 있', '신을 믿', '종교', '기도'],
  hope: ['희망', '나아질', '괜찮아질'],
  favorite: ['좋아하는 거', '좋아하는 게', '제일 좋아'],
  hate: ['싫어하는', '제일 싫', '증오'],
  childhood: ['어릴 때', '어렸을 때', '어린 시절', '어린시절'],
  friend: ['친구', '절친', '믿는 사람'],
  drink: ['술 한', '술을', '술은', '술 마', '담배', '마실 거', '한잔'],
  morning: ['아침', '해 뜨', '일출'],
  night: ['밤이', '밤은', '오늘 밤', '자정'],
  promise: ['약속', '맹세', '보장해'],
  goodbye: ['잘 가', '안녕히', '다음에 봐', '작별'],
  compliment: ['멋있', '대단해', '최고야', '잘했어', '똑똑'],
  meaning: ['삶의 의미', '왜 사는', '사는 이유', '의미가 있'],
  real: ['너 진짜야', '너는 진짜', '실재', '꿈이야', '현실이야'],
  meta: ['게임이야', '이거 게임', '플레이어', '개발자', '너 ai', '너 인공지능'],
  animal: ['고양이', '강아지', '동물'],
  ocean: ['바다', '파도', '해변'],
  stars: ['별이', '별은', '별을', '우주', '달을 본'],
  bored: ['심심', '지루', '재미없'],
}

export const MORE_KEYWORDS_EN = {
  age: ['how old', 'your age', 'age'],
  place: ['where are we', 'what is this place', 'this place', 'where am i'],
  lien: ['lien', 'designer', 'who built'],
  aren: ['aren', 'dog tag'],
  dome: ['dome', 'the fence'],
  collapse: ['collapse', 'twenty years ago', '20 years ago', 'what happened back then'],
  guard: ['guard', 'guards', 'the guard', 'security', 'police', 'cops', 'riot squad'],
  rebels: ['rebel*', 'resistance', 'pirate broadcast'],
  auction: ['auction', 'bidding', 'bidder*', 'highest bid'],
  ledger: ['ledger', 'records book', 'partition*'],
  help_me: ['help me', 'save me', 'need help', 'please help'],
  together: ['come with me', 'together', 'partner*', 'join me', 'on my side'],
  leave: ['can i leave', 'i want to leave', 'quit', "i'm out", 'walk away'],
  hurt: ['hurt', 'bleeding', 'injured', 'wound*', 'in pain'],
  kill: ['kill me', 'going to kill', 'shoot me', 'hurt me'],
  lying: ['are you lying', "you're lying", 'liar', 'bullshit', 'scam'],
  secret: ['secret*', 'hiding something', "what aren't you telling"],
  regret: ['regret*', 'do it over', 'take it back'],
  happy: ['happy', 'happiness', 'joy'],
  love: ['what is love', 'ever loved', 'been in love', 'lover'],
  god: ['god', 'religion', 'pray*', 'believe in'],
  hope: ['hope', 'get better', 'be okay'],
  favorite: ['favorite', 'favourite', 'like most'],
  hate: ['hate', 'what do you hate', 'despise'],
  childhood: ['childhood', 'as a kid', 'as a child', 'growing up'],
  friend: ['friend*', 'best friend'],
  drink: ['booze', 'alcohol', 'cigarette*', 'smoke', 'a drink'],
  morning: ['morning', 'sunrise', 'dawn'],
  night: ['tonight', 'midnight', 'night'],
  promise: ['promise', 'swear', 'guarantee'],
  goodbye: ['goodbye', 'bye', 'see you', 'farewell'],
  compliment: ['cool', 'amazing', 'awesome', 'smart', 'well done', 'impressive'],
  meaning: ['meaning of life', 'why live', 'point of it', 'meaning'],
  real: ['are you real', 'is this real', 'a dream', 'reality'],
  meta: ['a game', 'video game', 'the player', 'the developer', 'are you an ai', 'chatbot'],
  animal: ['cat', 'cats', 'dog', 'dogs', 'animal*', 'bird*'],
  ocean: ['ocean', 'sea', 'waves', 'beach'],
  stars: ['star', 'stars', 'outer space', 'moon', 'galaxy'],
  bored: ['bored', 'boring', 'dull'],
}
